services:
  - type: web
    name: my-backend
    runtime: node
    repo: https://github.com/akash4142/backend
    branch: main
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    plan: free
    buildCommand: npm install
    startCommand: npm start
